title: Speedons 2026
baseline: Programme complet des runs
description: Site statique permettant de visualiser le planning Speedons 2026.

language: fr
languages:
  - code: fr
    name: Français
    locale: fr_FR

pages:
  body:
    highlight:
      enabled: false
